### PR TITLE
rocket 0.5 support

### PR DESCRIPTION
**Pull request by mbr**
This is not in a mergable state as rocket 0.5 has not been officially released. As soon as it is, this should hopefully do the trick though. Feel free to steal the code instead of merging this.

Compiles on stable (thanks to rocket 0.5) for me.

### CODE REVIEW

**Comment by lambda-fairy** [comment]
Thanks! Looks good to me. I'm happy to merge this when Rocket 0.5 is released.

**Comment by lambda-fairy** [comment]
```
error[E0277]: the trait bound `Cow<'_, str>: FromParam<'_>` is not satisfied
 --> lib.rs:112:20
  |
9 | fn hello<'a>(name: Cow<'a, str>) -> Markup {
  |                    ^^^^^^^^^^^^ the trait `FromParam<'_>` is not implemented for `Cow<'_, str>`
  |
  = note: required by `from_param`
```

Looks like the [docs](https://github.com/mbr/maud/blob/mbr/rocket-0.5/docs/content/web-frameworks.md#rocket) need to be updated as well.

**Comment by 10ne1** [comment]
FYI: I have successfully tested this PR with Rocket `v0.5.0-rc.1` and Rust stable.
